### ISSUE TITLE
Repeat 2.14 eval against gemini API

### ISSUE THREAD

**Issue by loarie** [inaturalist/iNaturalistMLWork#121]

**Comment by loarie** [comment]
See https://inaturalist.slack.com/archives/C4GS9KY9J/p1724025106394929

**Comment by sylvain-morin** [comment]
- [ ] [Get CV results from Gemini API](https://github.com/inaturalist/iNaturalistMLWork/issues/123)
- [ ] [Convert Gemini taxon results into iNaturalist taxonomy](https://github.com/inaturalist/iNaturalistMLWork/issues/124)
- [ ] [Calculate Gemini accuracy](https://github.com/inaturalist/iNaturalistMLWork/issues/125)

To discuss: [Advanced Gemini prompting idea](https://github.com/inaturalist/iNaturalistMLWork/issues/126)
