### ISSUE TITLE
assist mobile team with integration of geo to mobile

### ISSUE THREAD

**Issue by alexshepard** [inaturalist/iNaturalistMLWork#43]
Here's what we decided at the CV meeting on October 3:

**Required for iNat Next Hard Launch**:
- [x] [create mobile optimized geo model for 2.13](https://github.com/inaturalist/iNaturalistMLWork/issues/132)
- [x] [get geo model working in camera](https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/33)

**Strong nice to have for hard launch, may become necessary if the team decides that the Seek app is too slow while on retreat**:
- [x] [taxonomy rollup speedup](https://github.com/inaturalist/iNaturalistMLWork/issues/111)

**Would be cool for hard launch**:
- [x] #147

**Unclear priority for hard launch, and needs defining into a ticket:**
- [ ] online suggestions parity with online suggestions. we don't have a current ticket for this.

**Unscheduled**:
- [ ] [re-write cv camera](https://github.com/inaturalist/vision-camera-plugin-inatvision/issues/4)

**Comment by alexshepard** [comment]
Met with Johannes on Sept 26 we decided to make some separate tickets.

**Comment by alexshepard** [comment]
extending to iteration 16

**Comment by jtklein** [comment]
All remaining tasks have their own tickets now.
